 export const LOGIN_DATA= 'LOGIN_DATA';
 export const LOGOUT = 'LOGOUT';     
 export const GET_PROJECTS = 'GET_PROJECTS';
 export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
 export const POST_PROJECT ='POST_PROJECT';
 export const GET_EVENTS='GET_EVENTS';
 export const FIRST_EVENTS='FIRST_EVENTS';
 export const POST_EVENT='POST_EVENT';
 export const POST_STANDUP='POST_STANDUP';
 export const GET_STANDUP='GET_STANDUP';
 export const POST_SPRINT_PLANNING='POST_SPRINT_PLANNING';
 export const GET_SPRINT_PLANNING='GET_SPRINT_PLANNING';
 export const POST_SPRINT_REVIEW='POST_SPRINT_REVIEW';
 export const GET_SPRINT_REVIEW='GET_SPRINT_REVIEW';
 export const POST_SPRINT_RETRO='POST_SPRINT_RETRO';
 export const GET_SPRINT_RETRO='GET_SPRINT_RETRO';
 export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';     
 export const AUTH_ERROR = 'AUTH_ERROR';     
 export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';     
 export const USER_PHOTO = 'USER_PHOTO';
 export const GET_PROJECT_ID='GET_PROJECT_ID';
 export const GET_FIRST_ID='GET_FIRST_ID';
 export const JWT_TOKEN='JWT_TOKEN';
 export const CHART_STANDUP='CHART_STANDUP';
 export const CHART_SPRINT_PLANNING='CHART_SPRINT_PLANNING';
 export const CHART_SPRINT_REVIEW='CHART_SPRINT_REVIEW';
 export const CHART_SPRINT_RETRO='CHART_SPRINT_RETRO';
 export const CHART_STORIES='CHART_STORIES';
 export const TEAM_MEMBERS='TEAM_MEMBERS';
 
 
 


        